# Generated by Django 5.2.3 on 2025-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_alter_estudiante_nombre_alter_modulo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
